---
swagger: '2.0'
info:
  description: Network-Registry under UHI(Unified Health Interface)
  version: '1.0'
  title: Network-Registry Project
  termsOfService: termsOfServiceUrl
  contact:
    name: National Health Authority India
  license:
    name: License 1.0
    url: https://licenseUrl.com
host: localhost:9090
basePath: "/"
tags:
- name: registry-controller
  description: Registry Controller
- name: subscriber-controller
  description: Subscriber Controller
paths:
  "/api/delete/{id}":
    delete:
      tags:
      - registry-controller
      summary: deleteSubscriber
      operationId: deleteSubscriberUsingDELETE
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: OK
          schema:
            type: string
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  "/api/keys/{subscriberId}":
    get:
      tags:
      - registry-controller
      summary: getSubscriberKeys
      operationId: getSubscriberKeysUsingGET
      produces:
      - "*/*"
      parameters:
      - name: subscriberId
        in: path
        description: subscriberId
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              "$ref": "#/definitions/KeyDto"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/api/lookup":
    post:
      tags:
      - registry-controller
      summary: lookup
      operationId: lookupUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: requestData
        description: requestData
        required: true
        schema:
          "$ref": "#/definitions/LookupDto"
      responses:
        '200':
          description: OK
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/api/on_subscribe":
    post:
      tags:
      - subscriber-controller
      summary: onSubscriber
      operationId: onSubscriberUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: onSubscribeDto
        description: onSubscribeDto
        required: true
        schema:
          "$ref": "#/definitions/OnSubscribeDto"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/OnSubscribeResponseDto"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/api/subscribe":
    get:
      tags:
      - registry-controller
      summary: findAllSubscribers
      operationId: findAllSubscribersUsingGET
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              "$ref": "#/definitions/SubscriberDto"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
      - registry-controller
      summary: createSubscriber
      operationId: createSubscriberUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: subscriberData
        description: subscriberData
        required: true
        schema:
          "$ref": "#/definitions/SubscriberDto"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/SubscribeResponseDto"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/api/subscriber/{id}":
    get:
      tags:
      - registry-controller
      summary: findBySubscriberId
      operationId: findBySubscriberIdUsingGET
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/SubscriberDto"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
      - registry-controller
      summary: changeSubscriberStatus
      operationId: changeSubscriberStatusUsingPUT
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int32
      - in: body
        name: status
        description: status
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/SubscribeResponseDto"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/api/update":
    put:
      tags:
      - registry-controller
      summary: updateSubscriber
      operationId: updateSubscriberUsingPUT
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: subscriberData
        description: subscriberData
        required: true
        schema:
          "$ref": "#/definitions/SubscriberDto"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/SubscriberDto"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  KeyDto:
    type: object
    properties:
      privateKey:
        type: string
      publicKey:
        type: string
    title: KeyDto
  LookupDto:
    type: object
    properties:
      city:
        type: string
      country:
        type: string
      domain:
        type: string
      subscriber_id:
        type: string
      type:
        type: string
    title: LookupDto
  OnSubscribeDto:
    type: object
    properties:
      challenge:
        type: string
      subscriber_id:
        type: string
    title: OnSubscribeDto
  OnSubscribeResponseDto:
    type: object
    properties:
      answer:
        type: string
    title: OnSubscribeResponseDto
  SubscribeResponseDto:
    type: object
    properties:
      status:
        type: string
    title: SubscribeResponseDto
  SubscriberDto:
    type: object
    properties:
      challangeString:
        type: string
      city:
        type: string
      country:
        type: string
      createrUser:
        type: string
      domain:
        type: string
      encr_public_key:
        type: string
      id:
        type: integer
        format: int32
      participantId:
        type: integer
        format: int32
      pub_key_id:
        type: string
      radius:
        type: string
      signing_public_key:
        type: string
      status:
        type: string
      subscriber_id:
        type: string
      type:
        type: string
      unique_key_id:
        type: string
      updaterUser:
        type: string
      url:
        type: string
      valid_from:
        type: string
      valid_to:
        type: string
    title: SubscriberDto
