---
swagger: '2.0'
info:
  description: UHI(Unified Health Interface) is envisioned as an open protocol for various digital health services. UHI Network will be an open network of End User Applications (EUAs) and participating Health Service Provider (HSP) applications. UHI will enable a wide variety of digital health services between patients and health service providers (HSPs) including appointment booking, teleconsultation, service discovery and others.<br>
    
    <b>API Security</b><br>
    You need Authorization Token to consume APIs.
    <br><br><b>Gateway Signing</b>
    <br>The BG will send its signature in the Proxy-Authorization header in the exact same format as shown below -
    <ul><li><p>X-Gateway-Authorization:Signature keyId="{subscriber_id}|{unique_key_id}|{algorithm}" algorithm="xed25519" created="1606970629" expires="1607030629" headers="(created) (expires) digest" signature="Base64(BLAKE-512(signing string))"</p></li></ul>
    
    <p>The EUAs and HSPAs subscriber is expected to send an Authorization header (as defined in RFC 7235, Section 4.1) where the “auth-scheme” is “Signature” and the “auth-param” parameters <br>
    Below is the format of a EUA/HSPA Authorization header in the typical HTTP Signature format - </p>
    
    <ul><li><p>Authorization:Signature keyId
    ="{subscriber_id}|{unique_key_id}|{algorithm}"
    algorithm="xed25519" created="1606970629" expires="1607030629" headers="(created) (expires) digest" signature="Base64(BLAKE-512(signing string))"</p></li></ul>
    
    <p><b>Hashing Algorithm</b><br>
    For computing the digest of the request body, the hashing function will use the BLAKE-512 hashing algorithm. BLAKE is a cryptographic hash function based on Dan Bernstein’s ChaCha stream cipher. For more documentation on the BLAKE-512 algorithm, please go to RFC7693.<br></p>
    
    <p><b>Signing Algorithm</b><br>
    To digitally sign the singing string, the subscribers should use the “XEdDSA” signature scheme (or “XEd25519”). For the first version of UHI gateway, we’ll be using the XEd25519 Signature Scheme.<br></p>

  version: '1.0.0'
  title: UHI-Gateway API
  termsOfService: termsOfServiceUrl
  contact:
    name: National Health Authority India
  license:
    name: License 1.0
    url: https://licenseUrl.com
host: https://uhigatewaybeta.abdm.gov.in
basePath: "/"
tags:
  - name: Requestor
    description: Search requestor to broadcast the message over HSPAs
  - name: Responder
    description: Accepter for all the on_search response from the HSPAs
paths:
  "/api/v1/on_search":
    post:
      tags:
        - Responder
      summary: on_search response from HSPAs
      operationId: searchUsingPOST_1
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: request
          description: request
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Response"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/api/v1/search":
    post:
      tags:
        - Requestor
      summary: search request to HSPAs
      operationId: searchUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: headers
          in: header
          description: headers
          required: true
          type: string
        - in: body
          name: request
          description: request
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Response"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  Ack:
    type: object
    description: Describes the ACK response
    properties:
      status:
        description: Describe the status of the ACK response. If schema validation passes, status is ACK else it is NACK
        type: string
        enum:
          - ACK
          - NACK
    title: Ack
  Error:
    type: object
    properties:
      code:
        type: string
        description: UHI specific error code.
      message:
        type: string
        description: Human readable message describing the error
      path:
        type: string
        description: Path to json schema generating the error. Used only during json schema validation errors
      type:
        type: string
    title: Error
  Message:
    type: object
    properties:
      ack:
        "$ref": "#/definitions/Ack"
    title: Message
  Response:
    type: object
    properties:
      error:
        "$ref": "#/definitions/Error"
      message:
        "$ref": "#/definitions/Message"
    title: Response
